apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: default
data:
  database-name: wordpress
  my.cnf: |
    [mysqld]
    bind-address = 0.0.0.0
    default-authentication-plugin = mysql_native_password
    max_connections = 200
    innodb_buffer_pool_size = 128M
